services:
  opencart:
    build: tools
    user: 1000:1000
    ports:
      - "80:80"
    volumes:
      - ./upload:/var/www/html
      - ./storage:/var/www/storage
    depends_on:
      - mysql
    command: >
      bash -c "if [ ! -f /var/www/html/install.lock ]; then
                 wait-for-it mysql:3306 -t 60 &&
                 touch /var/www/html/install.lock;
               fi &&
               apache2-foreground"

  mysql:
    image: mariadb
    # ports:
    #   - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=opencart
      - MYSQL_DATABASE=opencart
    volumes:
      - my-data:/var/lib/mysql

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    ports:
      - "8888:8080"

  # redis:
  #   image: redis:latest

  # memcached:
  #   image: memcached:latest

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=opencart
  #     - POSTGRES_DB=opencart

volumes:
  my-data: